### ISSUE TITLE
Lookup denied (met dubbele namen)

### ISSUE THREAD

**Issue by GerdNL** [ossobv/pstore#22]
Hoi wallie,
Het viel mij vandaag op dat als ik b.v. 
pstore -c netflix in mijn account heb staan (linux user gerd)
en iemand anders gebruikt dezelfde naam op een ander account
dan krijg je de melding: user error: lookup denied (no permission or not found)

**Comment by wdoekes** [comment]
It is known. Although it's a confusing error, it's caused by a perfectly natural sequence of events:
- you're not necessarily allowed to "see" other peoples objects. So when trying to create one, you'll just get a permission denied.

Note that this error message has improved in newer tagged commits. Updating your pstore version should help:
```
pstore -c existing_object
...
user error: lookup denied (no permission to view/overwrite, or not found)
```
